niziapp/urls.py
from django.urls import path

from .views import (
    home, login_page, logout_page,
    register_page
)

app_name = 'niziapp'


urlpatterns = [
    path('', home, name='home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
]

niziaproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('niziapp.urls',
                     namespace='niziapp')),
]

niziapp/models.py
from django.db import models

# Create your models here.

niziapp/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'style': 'width: 200px;'
                               }))
    email = forms.CharField(max_length=30,
                            widget=forms.EmailInput(attrs={
                                'class': 'form-control',
                                'style': 'width: 200px;'
                            }))
    password = forms.CharField(max_length=30,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control',
                                   'style': 'width: 200px;'
                               }))

    password2 = forms.CharField(max_length=30,
                                label='Confirm password',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'style': 'width: 200px;'
                                }))

    class Meta:
        model = User
        fields = ['username', 'email',
                  'password', 'password2']

    # def clean_password(self):
    #     data = self.cleaned_data
    #     if data['password'] != self.password2:
    #         raise forms.ValidationError('Password did not match')

    #     return self.password


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'style': 'width: 200px;'
                               }))
    password = forms.CharField(max_length=30,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control',
                                   'style': 'width: 200px;'
                               }))

    # class Meta:
    #     model = User
    #     fields = ['username', 'password']

niziapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate, login, logout
)
from django.contrib.auth.decorators import (
    login_required
)
from django.contrib.auth.models import User
from django.contrib import messages

from .forms import (
    UserRegisterForm, UserLoginForm
)


@login_required
def home(request):
    return render(request,
                  'portal/home.html',
                  {})


def login_page(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = data['username']
            password = data['password']

            user = authenticate(username=username,
                                password=password)

            if user is None:
                messages.warning(request, 'Wrong username or password')
                return redirect('/login/')
            else:
                login(request, user)
                return redirect('/')
    else:
        form = UserLoginForm()

    return render(request,
                  'auth/login.html',
                  {'form': form})


def register_page(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            del data['password2']
            user = User.objects.create(**data)
            user.save()
            return redirect('/login/')
    else:
        form = UserRegisterForm()

    return render(request,
                  'auth/register.html',
                  {'form': form})


def logout_page(request):
    logout(request)
    return redirect('/login/')

niziapp/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    {% block title %}
        <title>Portal</title>
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'niziapp:home' %}">Homepage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'niziapp:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item" style="color: black;">
                                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
                                    Username: <em>{{ request.user }}</em>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="main">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock %}
</body>
</html>

niziapp/templates/portal/home.html
{% extends "base.html" %}

{% block title %}
    <title>Homepage</title>
{% endblock %}


{% block content %}

{% endblock %}